

% myData = table( Returns(2:availableTimePoints),...
%                 Std25Day(2:availableTimePoints),...
%                 Std250Day(2:availableTimePoints),...
%                 Indicator_Std(2:availableTimePoints),...
%                 Indicator_AverageVolume(2:availableTimePoints),...
%                 Indicator_DailyBand(2:availableTimePoints),...
%                 Indicator_Trailing25Day(2:availableTimePoints),...
%                 Indicator_Trailing200Day(2:availableTimePoints),...
%                 ReturnCategories(1:availableTimePoints-1),...
%                 'VariableNames',{'Returns','Std25Day','Std250Day','Indicator_Std','Indicator_AverageVolume','Indicator_DailyBand','Indicator_Trailing25Day','Indicator_Trailing200Day','ReturnCategories'});
%                 
%     
